### ISSUE TITLE
Spam abuse detected from the IP range

### ISSUE THREAD

**Issue by ArturoBravo111** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#168] opened 2024-06-04 02:50 UTC
# Module: 01
#### Step: 13 - Sign into your personal email account and open the message from Lynne Robbins.

Description of issue

We followed all the steps, and after sending the email, students received an immediate reply indicating Spam abuse detected from the IP range. We are using GoDeploy.

![Screenshot 2024-06-04 142954](https://github.com/MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator/assets/34762894/985e9dd6-d1e4-4d70-8f68-136cd20a755d)

**Comment by riswinto** [comment] 2024-06-17 15:19
@ArturoBravo111, has this continued to be an issue training for SC-400? I was unable to reproduce this issue, so I'm curious if this was an anomaly.

**Comment by riswinto** [comment] 2024-07-19 18:18
@ArturoBravo111, I believe this may have been a one-off issue. I'm closing this issue for now. Please let me know if you continue to experience this when conducting training for SC-400.

**Closed by riswinto** 2024-07-19 18:18 UTC
